# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from ._builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseShop(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Shop']] = 'Shop'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ShopActions[_PrismaModelT]':
        from .client import get_client

        return actions.ShopActions[_PrismaModelT](client or get_client(), cls)


class BaseProduct(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Product']] = 'Product'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ProductActions[_PrismaModelT]':
        from .client import get_client

        return actions.ProductActions[_PrismaModelT](client or get_client(), cls)


class BaseFaqItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['FaqItem']] = 'FaqItem'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.FaqItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.FaqItemActions[_PrismaModelT](client or get_client(), cls)


class BaseShopInfoChunk(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ShopInfoChunk']] = 'ShopInfoChunk'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ShopInfoChunkActions[_PrismaModelT]':
        from .client import get_client

        return actions.ShopInfoChunkActions[_PrismaModelT](client or get_client(), cls)


class BaseChannel(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Channel']] = 'Channel'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ChannelActions[_PrismaModelT]':
        from .client import get_client

        return actions.ChannelActions[_PrismaModelT](client or get_client(), cls)


class BaseEndUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EndUser']] = 'EndUser'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EndUserActions[_PrismaModelT]':
        from .client import get_client

        return actions.EndUserActions[_PrismaModelT](client or get_client(), cls)


class BaseConversation(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Conversation']] = 'Conversation'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ConversationActions[_PrismaModelT]':
        from .client import get_client

        return actions.ConversationActions[_PrismaModelT](client or get_client(), cls)


class BaseMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Message']] = 'Message'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.MessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.MessageActions[_PrismaModelT](client or get_client(), cls)


class BaseEvent(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Event']] = 'Event'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EventActions[_PrismaModelT]':
        from .client import get_client

        return actions.EventActions[_PrismaModelT](client or get_client(), cls)


class BaseOrder(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Order']] = 'Order'  # pyright: ignore[reportIncompatibleVariableOverride]

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.OrderActions[_PrismaModelT]':
        from .client import get_client

        return actions.OrderActions[_PrismaModelT](client or get_client(), cls)


