from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'User',
    'Shop',
    'Product',
    'FaqItem',
    'ShopInfoChunk',
    'Channel',
    'EndUser',
    'Conversation',
    'Message',
    'Event',
    'Order',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'User': {
        'shops': 'Shop',
    },
    'Shop': {
        'owner': 'User',
        'products': 'Product',
        'faqItems': 'FaqItem',
        'shopInfoChunks': 'ShopInfoChunk',
        'channels': 'Channel',
        'endUsers': 'EndUser',
        'conversations': 'Conversation',
        'events': 'Event',
        'orders': 'Order',
    },
    'Product': {
        'shop': 'Shop',
        'conversations': 'Conversation',
        'orders': 'Order',
    },
    'FaqItem': {
        'shop': 'Shop',
    },
    'ShopInfoChunk': {
        'shop': 'Shop',
    },
    'Channel': {
        'shop': 'Shop',
    },
    'EndUser': {
        'shop': 'Shop',
        'conversations': 'Conversation',
        'events': 'Event',
        'orders': 'Order',
    },
    'Conversation': {
        'shop': 'Shop',
        'endUser': 'EndUser',
        'product': 'Product',
        'messages': 'Message',
    },
    'Message': {
        'conversation': 'Conversation',
    },
    'Event': {
        'shop': 'Shop',
        'endUser': 'EndUser',
    },
    'Order': {
        'shop': 'Shop',
        'endUser': 'EndUser',
        'product': 'Product',
    },
}

# fmt: on